openapi: 3.0.1
info:
  title: REST API LLS
  description: LLS - Lehrlings Liefer System | Apprentice Delivery System
  contact:
    name: Lars-Thorsten Bilek
    email: lars.bilek@gmx.at
  version: "1.0"
servers:
- url: https://localhost:9002
  description: Generated server url
security:
- bearerAuth: []
tags:
- name: UserPortal
  description: UserPortal Management
paths:
  /api/user/:
    get:
      tags:
      - user-controller
      operationId: loadUser
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetailDTO'
    put:
      tags:
      - user-controller
      operationId: updateUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserDTO'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetailDTO'
  /api/portal/user/:
    get:
      tags:
      - UserPortal
      description: load All Users with Permission Admin or Mod - you can use Pagination
        and Filtering
      operationId: loadAllUsers
      parameters:
      - name: page
        in: query
        required: false
        schema:
          type: integer
          format: int32
      - name: pageSize
        in: query
        required: false
        schema:
          type: integer
          format: int32
      - name: searchTerm
        in: query
        required: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseWrapperUserOverviewPortalDTO'
    put:
      tags:
      - UserPortal
      operationId: updateUser_1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserPortalDTO'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetailPortalDTO'
    post:
      tags:
      - UserPortal
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserPortalDTO'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetailPortalDTO'
  /api/user/current-user:
    get:
      tags:
      - user-controller
      operationId: loadLoggedInUser
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoggedInUserDTO'
  /api/portal/user/{id}:
    get:
      tags:
      - UserPortal
      operationId: loadUserById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDetailPortalDTO'
components:
  schemas:
    UpdateUserDTO:
      required:
      - email
      - firstname
      - id
      - lastname
      - version
      type: object
      properties:
        id:
          type: string
        version:
          minimum: 0
          type: integer
          format: int32
        firstname:
          type: string
        lastname:
          type: string
        status:
          type: string
        phoneNumber:
          type: string
        location:
          type: string
        iban:
          type: string
        paypalLink:
          type: string
        email:
          type: string
    UserDetailDTO:
      type: object
      properties:
        id:
          type: string
        version:
          type: integer
          format: int32
        firstname:
          type: string
        lastname:
          type: string
        status:
          type: string
        phoneNumber:
          type: string
        location:
          type: string
        iban:
          type: string
        paypalLink:
          type: string
        email:
          type: string
    UpdateUserPortalDTO:
      required:
      - email
      - enabled
      - firstname
      - id
      - lastname
      type: object
      properties:
        id:
          type: string
        version:
          minimum: 0
          type: integer
          format: int32
        firstname:
          type: string
        lastname:
          type: string
        status:
          type: string
        phoneNumber:
          type: string
        location:
          type: string
        iban:
          type: string
        paypalLink:
          type: string
        email:
          type: string
        enabled:
          type: boolean
        roles:
          maxItems: 2147483647
          minItems: 1
          type: array
          items:
            type: string
            enum:
            - ADMIN
            - MOD
            - USER
    UserDetailPortalDTO:
      type: object
      properties:
        id:
          type: string
        version:
          type: integer
          format: int32
        firstname:
          type: string
        lastname:
          type: string
        status:
          type: string
        phoneNumber:
          type: string
        location:
          type: string
        iban:
          type: string
        paypalLink:
          type: string
        email:
          type: string
        roles:
          type: array
          items:
            type: string
            enum:
            - ADMIN
            - MOD
            - USER
        enabled:
          type: boolean
    CreateUserPortalDTO:
      required:
      - email
      - enabled
      - firstname
      - lastname
      type: object
      properties:
        firstname:
          type: string
        status:
          type: string
        lastname:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        location:
          type: string
        iban:
          type: string
        paypalLink:
          type: string
        enabled:
          type: boolean
        roles:
          maxItems: 2147483647
          minItems: 1
          type: array
          items:
            type: string
            enum:
            - ADMIN
            - MOD
            - USER
    LoggedInUserDTO:
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
        roles:
          type: array
          items:
            type: string
            enum:
            - ADMIN
            - MOD
            - USER
    ResponseWrapperUserOverviewPortalDTO:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/UserOverviewPortalDTO'
        totalElements:
          type: integer
          format: int64
    UserOverviewPortalDTO:
      type: object
      properties:
        id:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        email:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
