###
##### S P R I N G
###
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lls_dev
    username: lls_dev
    password: lls_dev
  flyway:
    locations: classpath:flyway/schema/common
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    database-platform:  org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

###
##### S W A G G E R   U I
###
springdoc:
  swagger-ui:
    path: /api/swagger

###
##### J W T   T O K E N
###
own:
  security:
    jwt:
      secret: adkjhhuiaeuJABHGFIZW56749847894GBFDIkhgbdvhsdsuohefb6525484
      expires-in-minutes: 60
      issuer: lls_application
    password:
      initial_password: new_user_2023_
