###
##### S P R I N G
###
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lls_dev
    username: lls_dev
    password: lls_dev
  flyway:
    locations: classpath:common
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    database-platform:  org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9005/realms/lls_dev

###
##### S W A G G E R   U I
###
springdoc:
  swagger-ui:
    path: /api/swagger

###
##### S W A G G E R   U I
###
own:
  jwt:
    auth:
      converter:
        resource-client: backend
  keycloak:
    realm: lls_dev
    server-url: http://localhost:9005
    username: Backend_Admin_Client
    password: Backend_Admin_Client_2023_!
    client-secret: n6NgTPxrVcayScO18bD6bfuVAzs4PRQX
    default:
      password: LLS_DEV_PASSWORT_2023_

###
##### S S L
###
server:
  ssl:
    key-store: classpath:lls_dev.p12
    key-store-password: lls_dev_password
    key-store-type: pkcs12
    key-alias: lls_dev
    key-password: lls_dev_password
  port: 9002